include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact_name: totem-left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact_name: totem-right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact_name: totem-dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact_name: totem-settings-reset
